# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
production:
  adapter: postgresql
  database: db4f4ta83omie2
  username: ernjomslhvtfnq
  password: a292811489a33be360fd082756f4681627cfd9e6814041f755c38aca0578efcc
  host: ec2-54-221-241-23.compute-1.amazonaws.com
  port: 5432

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000